const ROLES = { OWNER: 'owner', ADMIN: 'admin', USER: 'user' };

const STATUS = { ACTIVE: 'active', PENDING: 'pending' };

const VISIBILITY = { PUBLIC: 'public', PRIVATE: 'private' };

const LIMITS = {
  MAX_TITLE: 200,
  MAX_CONTENT: 100_000,
  MAX_BPM: 300,
  MIN_BPM: 1,
  MAX_SETLIST_NAME: 200,
  MAX_CHANGELOG_VERSION: 50,
  MAX_CHANGELOG_TITLE: 200,
  MAX_CHANGELOG_SUMMARY: 1000,
  MAX_CHANGELOG_BODY: 20_000,
  MAX_PERFORMANCE_KEY: 20,
  MAX_SETLIST_NOTE: 2000,
  MAX_IMPORT: 500,
  DEMO_MAX_IMPORT: 20,
  MAX_REORDER: 1000,
  MAX_YOUTUBE_URL: 500,
  TRANSPOSE_MIN: -12,
  TRANSPOSE_MAX: 12,
  USERNAME_MIN: 3,
  USERNAME_MAX: 50,
  PASSWORD_MIN: 6,
  MAX_BODY_JSON: '18mb',
  MAX_PREFERRED_LANGUAGES: 10,
};

module.exports = {
  ROLES,
  STATUS,
  VISIBILITY,
  LIMITS,
};
